apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: results
  name: results
  namespace: federated-learning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
